### ISSUE TITLE
Divider is blured 

### ISSUE THREAD

**Issue by AleksBaikalsky** [sneas/img-comparison-slider#91] opened 2022-07-17 08:14 UTC
Because divider position can get not an integer value, browsers render divider width smoothing/blur

**Comment by sneas** [comment] 2022-07-17 08:29
How can I recreate this issue?

**Comment by sneas** [comment] 2022-07-17 08:32
I think this might be because the devider position is set in percents, not in pixels.

**Comment by sneas** [comment] 2022-07-17 08:51
But I’m struggling to reproduce the issue. Perhaps, the issue could be better reproduced on a non-retina screen. What kind of screen are you using?

**Comment by AleksBaikalsky** [comment] 2022-07-18 09:53
> I think this might be because the divider position is set in percents, not in pixels.
yes

I see this blur on all desktop and laptop screens. 14' FHD laptop, 32' UHD desktop - when system and browser scale settings is 100% (not 150% or 200% as it is often set on high pixel density screens by default)

**Comment by sneas** [comment] 2022-07-18 10:01
That's unfortunate. I've just checked the issue on a 4k TV, the lowest density screen I have, and I still can't see the issue. Do you mind uploading a problematic screenshot? Also, what browser are you using?

**Comment by sneas** [comment] 2022-07-31 11:00
Closing this issue for now. Feel free to reopen it with more details.

**Closed by sneas** 2022-07-31 11:00 UTC
